/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DutiesRouteImport } from './routes/duties'
import { Route as DeparturesRouteImport } from './routes/departures'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCronNightlyExportRouteImport } from './routes/api/public/cron/nightly-export'
import { Route as ApiPublicRouteIconUserFileRouteImport } from './routes/api/public/route-icon/$user/$file'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DutiesRoute = DutiesRouteImport.update({
  id: '/duties',
  path: '/duties',
  getParentRoute: () => rootRouteImport,
} as any)
const DeparturesRoute = DeparturesRouteImport.update({
  id: '/departures',
  path: '/departures',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNightlyExportRoute =
  ApiPublicCronNightlyExportRouteImport.update({
    id: '/api/public/cron/nightly-export',
    path: '/api/public/cron/nightly-export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRouteIconUserFileRoute =
  ApiPublicRouteIconUserFileRouteImport.update({
    id: '/api/public/route-icon/$user/$file',
    path: '/api/public/route-icon/$user/$file',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/departures': typeof DeparturesRoute
  '/duties': typeof DutiesRoute
  '/login': typeof LoginRoute
  '/api/public/cron/nightly-export': typeof ApiPublicCronNightlyExportRoute
  '/api/public/route-icon/$user/$file': typeof ApiPublicRouteIconUserFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/departures': typeof DeparturesRoute
  '/duties': typeof DutiesRoute
  '/login': typeof LoginRoute
  '/api/public/cron/nightly-export': typeof ApiPublicCronNightlyExportRoute
  '/api/public/route-icon/$user/$file': typeof ApiPublicRouteIconUserFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/departures': typeof DeparturesRoute
  '/duties': typeof DutiesRoute
  '/login': typeof LoginRoute
  '/api/public/cron/nightly-export': typeof ApiPublicCronNightlyExportRoute
  '/api/public/route-icon/$user/$file': typeof ApiPublicRouteIconUserFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/departures'
    | '/duties'
    | '/login'
    | '/api/public/cron/nightly-export'
    | '/api/public/route-icon/$user/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/departures'
    | '/duties'
    | '/login'
    | '/api/public/cron/nightly-export'
    | '/api/public/route-icon/$user/$file'
  id:
    | '__root__'
    | '/'
    | '/departures'
    | '/duties'
    | '/login'
    | '/api/public/cron/nightly-export'
    | '/api/public/route-icon/$user/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeparturesRoute: typeof DeparturesRoute
  DutiesRoute: typeof DutiesRoute
  LoginRoute: typeof LoginRoute
  ApiPublicCronNightlyExportRoute: typeof ApiPublicCronNightlyExportRoute
  ApiPublicRouteIconUserFileRoute: typeof ApiPublicRouteIconUserFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duties': {
      id: '/duties'
      path: '/duties'
      fullPath: '/duties'
      preLoaderRoute: typeof DutiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departures': {
      id: '/departures'
      path: '/departures'
      fullPath: '/departures'
      preLoaderRoute: typeof DeparturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/nightly-export': {
      id: '/api/public/cron/nightly-export'
      path: '/api/public/cron/nightly-export'
      fullPath: '/api/public/cron/nightly-export'
      preLoaderRoute: typeof ApiPublicCronNightlyExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/route-icon/$user/$file': {
      id: '/api/public/route-icon/$user/$file'
      path: '/api/public/route-icon/$user/$file'
      fullPath: '/api/public/route-icon/$user/$file'
      preLoaderRoute: typeof ApiPublicRouteIconUserFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeparturesRoute: DeparturesRoute,
  DutiesRoute: DutiesRoute,
  LoginRoute: LoginRoute,
  ApiPublicCronNightlyExportRoute: ApiPublicCronNightlyExportRoute,
  ApiPublicRouteIconUserFileRoute: ApiPublicRouteIconUserFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
