/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SaeRouteImport } from './routes/sae'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DutiesRouteImport } from './routes/duties'
import { Route as DeparturesRouteImport } from './routes/departures'
import { Route as CorrespondancesRouteImport } from './routes/correspondances'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SaeIndexRouteImport } from './routes/sae.index'
import { Route as ApiPublicGtfsAlertsRouteImport } from './routes/api/public/gtfs-alerts'
import { Route as ApiPublicCronNightlyExportRouteImport } from './routes/api/public/cron/nightly-export'
import { Route as ApiPublicRouteIconUserFileRouteImport } from './routes/api/public/route-icon/$user/$file'

const SaeRoute = SaeRouteImport.update({
  id: '/sae',
  path: '/sae',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DutiesRoute = DutiesRouteImport.update({
  id: '/duties',
  path: '/duties',
  getParentRoute: () => rootRouteImport,
} as any)
const DeparturesRoute = DeparturesRouteImport.update({
  id: '/departures',
  path: '/departures',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrespondancesRoute = CorrespondancesRouteImport.update({
  id: '/correspondances',
  path: '/correspondances',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaeIndexRoute = SaeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SaeRoute,
} as any)
const ApiPublicGtfsAlertsRoute = ApiPublicGtfsAlertsRouteImport.update({
  id: '/api/public/gtfs-alerts',
  path: '/api/public/gtfs-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNightlyExportRoute =
  ApiPublicCronNightlyExportRouteImport.update({
    id: '/api/public/cron/nightly-export',
    path: '/api/public/cron/nightly-export',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRouteIconUserFileRoute =
  ApiPublicRouteIconUserFileRouteImport.update({
    id: '/api/public/route-icon/$user/$file',
    path: '/api/public/route-icon/$user/$file',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/correspondances': typeof CorrespondancesRoute
  '/departures': typeof DeparturesRoute
  '/duties': typeof DutiesRoute
  '/login': typeof LoginRoute
  '/sae': typeof SaeRouteWithChildren
  '/sae/': typeof SaeIndexRoute
  '/api/public/gtfs-alerts': typeof ApiPublicGtfsAlertsRoute
  '/api/public/cron/nightly-export': typeof ApiPublicCronNightlyExportRoute
  '/api/public/route-icon/$user/$file': typeof ApiPublicRouteIconUserFileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/correspondances': typeof CorrespondancesRoute
  '/departures': typeof DeparturesRoute
  '/duties': typeof DutiesRoute
  '/login': typeof LoginRoute
  '/sae': typeof SaeIndexRoute
  '/api/public/gtfs-alerts': typeof ApiPublicGtfsAlertsRoute
  '/api/public/cron/nightly-export': typeof ApiPublicCronNightlyExportRoute
  '/api/public/route-icon/$user/$file': typeof ApiPublicRouteIconUserFileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/correspondances': typeof CorrespondancesRoute
  '/departures': typeof DeparturesRoute
  '/duties': typeof DutiesRoute
  '/login': typeof LoginRoute
  '/sae': typeof SaeRouteWithChildren
  '/sae/': typeof SaeIndexRoute
  '/api/public/gtfs-alerts': typeof ApiPublicGtfsAlertsRoute
  '/api/public/cron/nightly-export': typeof ApiPublicCronNightlyExportRoute
  '/api/public/route-icon/$user/$file': typeof ApiPublicRouteIconUserFileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/correspondances'
    | '/departures'
    | '/duties'
    | '/login'
    | '/sae'
    | '/sae/'
    | '/api/public/gtfs-alerts'
    | '/api/public/cron/nightly-export'
    | '/api/public/route-icon/$user/$file'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/correspondances'
    | '/departures'
    | '/duties'
    | '/login'
    | '/sae'
    | '/api/public/gtfs-alerts'
    | '/api/public/cron/nightly-export'
    | '/api/public/route-icon/$user/$file'
  id:
    | '__root__'
    | '/'
    | '/correspondances'
    | '/departures'
    | '/duties'
    | '/login'
    | '/sae'
    | '/sae/'
    | '/api/public/gtfs-alerts'
    | '/api/public/cron/nightly-export'
    | '/api/public/route-icon/$user/$file'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorrespondancesRoute: typeof CorrespondancesRoute
  DeparturesRoute: typeof DeparturesRoute
  DutiesRoute: typeof DutiesRoute
  LoginRoute: typeof LoginRoute
  SaeRoute: typeof SaeRouteWithChildren
  ApiPublicGtfsAlertsRoute: typeof ApiPublicGtfsAlertsRoute
  ApiPublicCronNightlyExportRoute: typeof ApiPublicCronNightlyExportRoute
  ApiPublicRouteIconUserFileRoute: typeof ApiPublicRouteIconUserFileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sae': {
      id: '/sae'
      path: '/sae'
      fullPath: '/sae'
      preLoaderRoute: typeof SaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duties': {
      id: '/duties'
      path: '/duties'
      fullPath: '/duties'
      preLoaderRoute: typeof DutiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departures': {
      id: '/departures'
      path: '/departures'
      fullPath: '/departures'
      preLoaderRoute: typeof DeparturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correspondances': {
      id: '/correspondances'
      path: '/correspondances'
      fullPath: '/correspondances'
      preLoaderRoute: typeof CorrespondancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sae/': {
      id: '/sae/'
      path: '/'
      fullPath: '/sae/'
      preLoaderRoute: typeof SaeIndexRouteImport
      parentRoute: typeof SaeRoute
    }
    '/api/public/gtfs-alerts': {
      id: '/api/public/gtfs-alerts'
      path: '/api/public/gtfs-alerts'
      fullPath: '/api/public/gtfs-alerts'
      preLoaderRoute: typeof ApiPublicGtfsAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/nightly-export': {
      id: '/api/public/cron/nightly-export'
      path: '/api/public/cron/nightly-export'
      fullPath: '/api/public/cron/nightly-export'
      preLoaderRoute: typeof ApiPublicCronNightlyExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/route-icon/$user/$file': {
      id: '/api/public/route-icon/$user/$file'
      path: '/api/public/route-icon/$user/$file'
      fullPath: '/api/public/route-icon/$user/$file'
      preLoaderRoute: typeof ApiPublicRouteIconUserFileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SaeRouteChildren {
  SaeIndexRoute: typeof SaeIndexRoute
}

const SaeRouteChildren: SaeRouteChildren = {
  SaeIndexRoute: SaeIndexRoute,
}

const SaeRouteWithChildren = SaeRoute._addFileChildren(SaeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorrespondancesRoute: CorrespondancesRoute,
  DeparturesRoute: DeparturesRoute,
  DutiesRoute: DutiesRoute,
  LoginRoute: LoginRoute,
  SaeRoute: SaeRouteWithChildren,
  ApiPublicGtfsAlertsRoute: ApiPublicGtfsAlertsRoute,
  ApiPublicCronNightlyExportRoute: ApiPublicCronNightlyExportRoute,
  ApiPublicRouteIconUserFileRoute: ApiPublicRouteIconUserFileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
